version: '2.3'

services:
  auth-flow-service:
    build: .
    command: ["npm", "run", "start:dev"]
    container_name: auth-flow-service
    env_file: .env
    image: auth-service:1.0.1
    networks:
      - backend
    ports:
      - "4000:4000"
    volumes:
      - type: bind
        source: .
        target: /home/api
  mongo-db:
    container_name: mongo-db
    image: "mongo:4-xenial"
    networks:
      - backend
    ports:
      - "27017:27017"
    command: --auth --bind_ip 0.0.0.0 --journal --oplogSize 192 --enableMajorityReadConcern
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - type: bind
        source: ./data/db
        target: /data/db

networks:
  backend:
    name: my_app_net
