FROM node:lts-alpine3.13

ENV HOME=/home
ENV NODE_ENV=production
ENV PORT=8080
ENV TZ=Asia/Kuala_Lumpur

RUN apk --no-cache update \
  && apk --no-cache upgrade \
  && apk add --update --no-cache curl py-pip \
  && apk --no-cache add tzdata

EXPOSE $PORT

WORKDIR $HOME/api

COPY package*.json ./
RUN npm install --production \
  && npm cache clean --force
COPY . .

RUN adduser -S node-app
RUN chown -R node-app $HOME/api
USER node-app

CMD npm run start:prod
